Repository SaturdayNeighborhoodHealthClinic/osler, pull requests merged in 2018-12, with the labels that each got.

#166 Add attempts to fix workup form submission.
  workup/forms.py
  workup/templates/workup/appended_radios.html
  workup/test_views.py
Labels: awaiting-review, bug

#192 Coloring of workup units errors
  workup/templates/workup/appended_radios.html
  workup/test_views.py
Labels: bug

#187 Check the next parameter in the choose-role view for external urls.
  pttrack/test_views.py
  pttrack/views.py
Labels: bug, high priority

#193 Fixed datetimepicker for appointment, followup, pttrack, and referral
  appointment/forms.py
  followup/forms.py
  pttrack/forms.py
  referral/forms.py
Labels: bug

#191 Add is_active field to ReferralType
  pttrack/migrations/0007_referraltype_is_active.py
  pttrack/models.py
  referral/tests.py
  referral/views.py
Labels: awaiting-review, enhancement
