Repository SaturdayNeighborhoodHealthClinic/osler, pull requests merged in 2019-03, with the labels that each got.

#206 Fixed DateTime tests
  appointment/test_views.py
  appointment/views.py
Labels: awaiting-review, bug

#205 Upgrade to django 1.11
  appointment/test_views.py
  followup/fixtures/followup.json
  pttrack/decorators.py
  pttrack/fixtures/pttrack.json
  pttrack/test_views.py
  pttrack/urls.py
  referral/models.py
  requirements.txt
  scripts/init_db.py
  workup/fixtures/workup.json
Labels: awaiting-review, enhancement

#208 Update configurations for django 1.11
  osler/deploy_settings.py
  osler/wsgi.py
Labels: bug

#188 Page view logs for all pages
  audit/__init__.py
  audit/admin.py
  audit/apps.py
  audit/middleware.py
  audit/migrations/0001_initial.py
  audit/migrations/__init__.py
  audit/models.py
  audit/tests.py
  osler.sublime-project
  osler/base_settings.py
  pttrack/admin.py
  pttrack/models.py
Labels: enhancement

#185 Improve patient detail template
  appointment/templates/appointment/blurbs/followup-blurb.html
  pttrack/models.py
  pttrack/templates/pttrack/blurbs/action-item-blurb-active.html
  pttrack/templates/pttrack/blurbs/base-completable-blurb.html
  pttrack/templates/pttrack/patient_detail.html
  pttrack/views.py
  referral/models.py
Labels: awaiting-review, enhancement

#197 Added action instruction and completion filters for Action item admin panel
  pttrack/admin.py
Labels: enhancement

#210 Move to python 3
  .circleci/config.yml
  api/test.py
  appointment/models.py
  appointment/templates/appointment/appointment_list.html
  appointment/test_views.py
  audit/models.py
  demographics/migrations/0001_squashed_0003_auto_20170623_1048.py
  demographics/models.py
  demographics/urls.py
  followup/admin.py
  followup/models.py
  followup/tests.py
  followup/urls.py
  pttrack/migrations/0001_squashed_0010_auto_20170623_1300.py
  pttrack/models.py
  pttrack/test_forms.py
  pttrack/test_utils.py
  pttrack/test_validators.py
  pttrack/test_views.py
  referral/forms.py
  referral/models.py
  referral/tests.py
  referral/urls.py
  workup/admin.py
  workup/migrations/0001_initial.py
  workup/models.py
  workup/test_models.py
  workup/urls.py
Labels: enhancement

#214 Bump django-simple-history version, w migrations.
  followup/migrations/0003_simplehistory_add_v2_migrations_20190324_1133.py
  requirements.txt
  workup/migrations/0003_historicalworkup_add_attending_validator_20190324_1133.py
Labels: enhancement
